name = "astro2"
compatibility_date = "2024-01-01"

[site]
bucket = "./.next/static"

[build]
command = "pnpm build"

[build.upload]
format = "service-worker"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

# 环境变量绑定
[vars]
NODE_ENV = "production"

# 兼容性标志
[compatibility_flags]
nodejs_compat = true 