import { useEffect, useState } from 'react'
import { 
  Crown, Calendar, User, Database, Shield, Check, Loader2,
  Sparkles, ExternalLink, CheckCircle, AlertTriangle, Trash2,
  Gift, Plus, ChevronRight, Star, Heart, Settings, Search,
  Menu, X, ArrowRight, ArrowLeft, Home, Clock, Save, BarChart3,
  Edit, Trash, Archive, Inbox, Package, Award, Target, Layers,
  Grid, List, MoreVertical, MoreHorizontal, Circle, Square,
  Triangle, Hexagon, Octagon, Bookmark, Filter, Sliders,
  Terminal, Code, Link, Link2, Anchor, Compass, Navigation,
  Navigation2, Map, Crosshair, ZoomIn, ZoomOut, Maximize,
  Maximize2, Minimize, Minimize2, Move, Cpu, Server, Monitor,
  Smartphone, Tablet, Watch, Tv, Radio, Speaker, Bluetooth,
  Cast, Airplay, Power, PowerOff, HardDrive, Disc, Activity,
  Feather, Command, Hash, Type, Bold, Italic, Underline,
  Strikethrough, AlignLeft, AlignCenter, AlignRight, AlignJustify,
  Columns, Sidebar, Layout, LayoutDashboard, LayoutGrid, LayoutList,
  LayoutTemplate
} from 'lucide-react'

// 图标名称到组件的映射
const iconComponents: Record<string, any> = {
  Crown, Calendar, User, Database, Shield, Check, Loader2,
  Sparkles, ExternalLink, CheckCircle, AlertTriangle, Trash2,
  Gift, Plus, ChevronRight, Star, Heart, Settings, Search,
  Menu, X, ArrowRight, ArrowLeft, Home, Clock, Save, BarChart3,
  Edit, Trash, Archive, Inbox, Package, Award, Target, Layers,
  Grid, List, MoreVertical, MoreHorizontal, Circle, Square,
  Triangle, Hexagon, Octagon, Bookmark, Filter, Sliders,
  Terminal, Code, Link, Link2, Anchor, Compass, Navigation,
  Navigation2, Map, Crosshair, ZoomIn, ZoomOut, Maximize,
  Maximize2, Minimize, Minimize2, Move, Cpu, Server, Monitor,
  Smartphone, Tablet, Watch, Tv, Radio, Speaker, Bluetooth,
  Cast, Airplay, Power, PowerOff, HardDrive, Disc, Activity,
  Feather, Command, Hash, Type, Bold, Italic, Underline,
  Strikethrough, AlignLeft, AlignCenter, AlignRight, AlignJustify,
  Columns, Sidebar, Layout, LayoutDashboard, LayoutGrid, LayoutList,
  LayoutTemplate
}

// 图标名称到emoji的映射
const iconFallbacks: Record<string, string> = {
  Crown: '👑',
  Calendar: '📅',
  User: '👤',
  Database: '💾',
  Download: '⬇️',
  Upload: '⬆️',
  RotateCcw: '🔄',
  Shield: '🛡️',
  CheckCircle: '✅',
  AlertTriangle: '⚠️',
  Trash2: '🗑️',
  Loader2: '⏳',
  Sparkles: '✨',
  ExternalLink: '🔗',
  Check: '✓',
  Gift: '🎁',
  Plus: '➕',
  Minus: '➖',
  ChevronRight: '›',
  ChevronLeft: '‹',
  Star: '⭐',
  Heart: '❤️',
  Settings: '⚙️',
  Search: '🔍',
  Menu: '☰',
  X: '✕',
  ArrowRight: '→',
  ArrowLeft: '←',
  Info: 'ℹ️',
  Mail: '✉️',
  Eye: '👁️',
  EyeOff: '🙈',
  Lock: '🔒',
  Unlock: '🔓',
  Key: '🔑',
  Home: '🏠',
  Clock: '🕐',
  Timer: '⏱️',
  Zap: '⚡',
  Award: '🏆',
  TrendingUp: '📈',
  TrendingDown: '📉',
  BarChart: '📊',
  PieChart: '🥧',
  Activity: '💓',
  Globe: '🌍',
  MapPin: '📍',
  Phone: '📱',
  MessageCircle: '💬',
  Send: '✈️',
  Share: '📤',
  Copy: '📋',
  Clipboard: '📋',
  FileText: '📄',
  Folder: '📁',
  Save: '💾',
  Printer: '🖨️',
  Wifi: '📶',
  WifiOff: '📵',
  Battery: '🔋',
  Volume: '🔊',
  VolumeX: '🔇',
  Sun: '☀️',
  Moon: '🌙',
  Cloud: '☁️',
  Umbrella: '☂️',
  Coffee: '☕',
  ShoppingCart: '🛒',
  CreditCard: '💳',
  DollarSign: '💵',
  Percent: '%',
  Hash: '#',
  AtSign: '@',
  Image: '🖼️',
  Camera: '📷',
  Video: '📹',
  Mic: '🎤',
  MicOff: '🔇',
  Headphones: '🎧',
  Music: '🎵',
  Film: '🎬',
  Book: '📚',
  Bookmark: '🔖',
  Tag: '🏷️',
  Flag: '🚩',
  Bell: '🔔',
  BellOff: '🔕',
  AlertCircle: '⚠️',
  HelpCircle: '❓',
  ThumbsUp: '👍',
  ThumbsDown: '👎',
  Smile: '😊',
  Frown: '😔',
  Users: '👥',
  UserPlus: '👤+',
  UserMinus: '👤-',
  UserCheck: '👤✓',
  UserX: '👤✕',
  LogIn: '➡️',
  LogOut: '⬅️',
  RefreshCw: '🔄',
  RefreshCcw: '🔄',
  Repeat: '🔁',
  Shuffle: '🔀',
  Play: '▶️',
  Pause: '⏸️',
  Stop: '⏹️',
  SkipForward: '⏭️',
  SkipBack: '⏮️',
  FastForward: '⏩',
  Rewind: '⏪',
  ChevronUp: '⌃',
  ChevronDown: '⌄',
  ChevronsUp: '⏫',
  ChevronsDown: '⏬',
  ChevronsLeft: '⏪',
  ChevronsRight: '⏩',
  Edit: '✏️',
  Edit2: '✏️',
  Edit3: '✏️',
  Trash: '🗑️',
  Archive: '📦',
  Inbox: '📥',
  Package: '📦',
  Gift: '🎁',
  Award: '🏆',
  Target: '🎯',
  Layers: '📚',
  Grid: '⚏',
  List: '📋',
  MoreVertical: '⋮',
  MoreHorizontal: '⋯',
  Circle: '○',
  Square: '□',
  Triangle: '△',
  Hexagon: '⬡',
  Octagon: '⬢',
  Star: '⭐',
  Heart: '❤️',
  Bookmark: '🔖',
  Filter: '🔧',
  Sliders: '🎚️',
  Terminal: '💻',
  Code: '</> ',
  Link: '🔗',
  Link2: '🔗',
  Anchor: '⚓',
  Compass: '🧭',
  Navigation: '🧭',
  Navigation2: '🧭',
  Map: '🗺️',
  Crosshair: '⊕',
  ZoomIn: '🔍+',
  ZoomOut: '🔍-',
  Maximize: '⛶',
  Maximize2: '⛶',
  Minimize: '⊖',
  Minimize2: '⊖',
  Move: '✥',
  Cpu: '🖥️',
  Server: '🖥️',
  Monitor: '🖥️',
  Smartphone: '📱',
  Tablet: '📱',
  Watch: '⌚',
  Tv: '📺',
  Radio: '📻',
  Speaker: '🔊',
  Bluetooth: '📶',
  Cast: '📶',
  Airplay: '📶',
  Power: '⚡',
  PowerOff: '⭕',
  HardDrive: '💾',
  Disc: '💿',
  Loader: '⏳',
  Activity: '💓',
  Feather: '🪶',
  Command: '⌘',
  Hash: '#',
  Type: 'T',
  Bold: 'B',
  Italic: 'I',
  Underline: 'U',
  Strikethrough: 'S',
  AlignLeft: '⫦',
  AlignCenter: '⫥',
  AlignRight: '⫧',
  AlignJustify: '⫨',
  Columns: '‖',
  Sidebar: '⫟',
  Layout: '⚏',
  LayoutDashboard: '⚏',
  LayoutGrid: '⚏',
  LayoutList: '☰',
  LayoutTemplate: '⚏'
}

interface SafeIconProps {
  icon?: string
  fallback?: string
  className?: string
  [key: string]: any
}

export function SafeIcon({ icon, fallback, className, ...props }: SafeIconProps) {
  // 直接从预加载的图标中获取
  const IconComponent = icon ? iconComponents[icon] : null
  
  // 如果有图标组件，渲染它
  if (IconComponent) {
    return <IconComponent className={className} {...props} />
  }

  // 使用提供的后备方案或默认后备方案
  const fallbackEmoji = fallback || iconFallbacks[icon || ''] || '○'
  return <span className={className} {...props}>{fallbackEmoji}</span>
}

// 导出常用图标的包装组件
export const SafeCrown = (props: Omit<SafeIconProps, 'icon'>) => 
  <SafeIcon icon="Crown" {...props} />

export const SafeCheck = (props: Omit<SafeIconProps, 'icon'>) => 
  <SafeIcon icon="Check" {...props} />

export const SafeLoader = (props: Omit<SafeIconProps, 'icon'>) => 
  <SafeIcon icon="Loader2" {...props} />

export const SafeSparkles = (props: Omit<SafeIconProps, 'icon'>) => 
  <SafeIcon icon="Sparkles" {...props} />

export const SafeExternalLink = (props: Omit<SafeIconProps, 'icon'>) => 
  <SafeIcon icon="ExternalLink" {...props} /> 