'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import EnglishLayout from '@/components/EnglishLayout'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { ArrowLeft, ArrowRight, RotateCcw, RefreshCw, Sparkles, Info, Star } from 'lucide-react'

export default function WuxingShengKePage() {
  const router = useRouter()
  const [selectedElement, setSelectedElement] = useState<string | null>(null)

  const elements = [
    {
      name: 'Wood (木 - mù)',
      color: 'from-green-100 to-emerald-200 dark:from-green-900/40 dark:to-emerald-800/40',
      textColor: 'text-green-700 dark:text-green-300',
      description: 'Growth, creativity, flexibility, expansion',
      generates: 'Fire',
      generatedBy: 'Water',
      destroys: 'Earth',
      destroyedBy: 'Metal',
      emoji: '🌱'
    },
    {
      name: 'Fire (火 - huǒ)',
      color: 'from-red-100 to-rose-200 dark:from-red-900/40 dark:to-rose-800/40',
      textColor: 'text-red-700 dark:text-red-300',
      description: 'Energy, passion, transformation, illumination',
      generates: 'Earth',
      generatedBy: 'Wood',
      destroys: 'Metal',
      destroyedBy: 'Water',
      emoji: '🔥'
    },
    {
      name: 'Earth (土 - tǔ)',
      color: 'from-amber-100 to-yellow-200 dark:from-amber-900/40 dark:to-yellow-800/40',
      textColor: 'text-amber-700 dark:text-amber-300',
      description: 'Stability, nourishment, grounding, support',
      generates: 'Metal',
      generatedBy: 'Fire',
      destroys: 'Water',
      destroyedBy: 'Wood',
      emoji: '🌍'
    },
    {
      name: 'Metal (金 - jīn)',
      color: 'from-gray-100 to-slate-200 dark:from-gray-900/40 dark:to-slate-800/40',
      textColor: 'text-gray-700 dark:text-gray-300',
      description: 'Structure, precision, clarity, determination',
      generates: 'Water',
      generatedBy: 'Earth',
      destroys: 'Wood',
      destroyedBy: 'Fire',
      emoji: '⚡'
    },
    {
      name: 'Water (水 - shuǐ)',
      color: 'from-blue-100 to-cyan-200 dark:from-blue-900/40 dark:to-cyan-800/40',
      textColor: 'text-blue-700 dark:text-blue-300',
      description: 'Flow, adaptability, wisdom, intuition',
      generates: 'Wood',
      generatedBy: 'Metal',
      destroys: 'Fire',
      destroyedBy: 'Earth',
      emoji: '💧'
    }
  ]

  const applications = [
    {
      title: 'Traditional Chinese Medicine (TCM)',
      description: 'Understanding how organs support or inhibit each other',
      icon: '🏥',
      color: 'bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800'
    },
    {
      title: 'Feng Shui',
      description: 'Arranging environments to promote harmonious energy flow',
      icon: '🏠',
      color: 'bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800'
    },
    {
      title: 'Martial Arts',
      description: 'Development of fighting styles and combat theories',
      icon: '🥋',
      color: 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800'
    },
    {
      title: 'Astrology & Divination',
      description: 'Applications in Chinese zodiac and fortune telling',
      icon: '⭐',
      color: 'bg-purple-50 dark:bg-purple-900/20 border-purple-200 dark:border-purple-800'
    }
  ]

  const ElementCard = ({ element, isSelected, onClick }: { element: typeof elements[0], isSelected: boolean, onClick: () => void }) => (
    <Card 
      className={`cursor-pointer transition-all duration-200 ${isSelected ? 'ring-2 ring-blue-500 shadow-lg' : 'hover:shadow-md'} bg-gradient-to-br ${element.color}`}
      onClick={onClick}
    >
      <CardContent className="p-4">
        <div className="flex items-center justify-between mb-2">
          <span className="text-2xl">{element.emoji}</span>
          <Badge variant="outline" className={element.textColor}>
            {element.name.split(' ')[0]}
          </Badge>
        </div>
        <h3 className={`font-semibold text-lg ${element.textColor}`}>
          {element.name}
        </h3>
        <p className="text-sm text-gray-600 dark:text-gray-300 mt-1">
          {element.description}
        </p>
        {isSelected && (
          <div className="mt-3 space-y-2 text-sm">
            <div className="flex items-center gap-2">
              <ArrowRight className="h-4 w-4 text-green-600" />
              <span>Generates: <strong>{element.generates}</strong></span>
            </div>
            <div className="flex items-center gap-2">
              <ArrowLeft className="h-4 w-4 text-blue-600" />
              <span>Generated by: <strong>{element.generatedBy}</strong></span>
            </div>
            <div className="flex items-center gap-2">
              <RefreshCw className="h-4 w-4 text-red-600" />
              <span>Destroys: <strong>{element.destroys}</strong></span>
            </div>
            <div className="flex items-center gap-2">
              <RotateCcw className="h-4 w-4 text-orange-600" />
              <span>Destroyed by: <strong>{element.destroyedBy}</strong></span>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )

  return (
    <EnglishLayout>
      <div className="max-w-4xl mx-auto p-4 space-y-6">
        {/* Header */}
        <div className="flex items-center gap-4 mb-6">
          <Button
            variant="ghost"
            onClick={() => router.back()}
            className="flex items-center gap-2 hover:bg-gray-100 dark:hover:bg-gray-800"
          >
            <ArrowLeft className="h-4 w-4" />
            Back
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
              Five Elements Generation & Destruction Cycles
            </h1>
            <p className="text-gray-600 dark:text-gray-300">
              Wu Xing (五行) - The fundamental cycles of creation and control
            </p>
          </div>
        </div>

        {/* Introduction */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              Introduction
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              The theory of Five Elements (五行 - Wǔ Xíng) is a fundamental concept in traditional Chinese philosophy used to explain a wide range of phenomena, from cosmic cycles to the workings of the human body. It involves two main cycles: the <strong>Generation Cycle</strong> (相生 - xiāngshēng) and the <strong>Destruction or Overcoming Cycle</strong> (相克 - xiāngkè).
            </p>
          </CardContent>
        </Card>

        {/* Five Elements Interactive */}
        <Card>
          <CardHeader>
            <CardTitle>The Five Elements</CardTitle>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Click on any element to see its relationships with others
            </p>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {elements.map((element) => (
                <ElementCard
                  key={element.name}
                  element={element}
                  isSelected={selectedElement === element.name}
                  onClick={() => setSelectedElement(
                    selectedElement === element.name ? null : element.name
                  )}
                />
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Generation Cycle */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ArrowRight className="h-5 w-5 text-green-600" />
              1. The Generation Cycle (相生 - xiāngshēng)
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              This cycle describes how each element gives rise to the next, representing a relationship of nourishment, creation, and support. It's a harmonious and creative cycle.
            </p>
            <div className="space-y-3">
              <div className="flex items-center gap-3 p-3 bg-green-50 dark:bg-green-900/20 rounded-lg">
                <span className="text-xl">🌱</span>
                <span className="font-semibold">Wood</span>
                <ArrowRight className="h-4 w-4 text-green-600" />
                <span className="text-xl">🔥</span>
                <span className="font-semibold">Fire</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Burning wood creates fire</span>
              </div>
              <div className="flex items-center gap-3 p-3 bg-red-50 dark:bg-red-900/20 rounded-lg">
                <span className="text-xl">🔥</span>
                <span className="font-semibold">Fire</span>
                <ArrowRight className="h-4 w-4 text-red-600" />
                <span className="text-xl">🌍</span>
                <span className="font-semibold">Earth</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Ash from fire becomes earth</span>
              </div>
              <div className="flex items-center gap-3 p-3 bg-amber-50 dark:bg-amber-900/20 rounded-lg">
                <span className="text-xl">🌍</span>
                <span className="font-semibold">Earth</span>
                <ArrowRight className="h-4 w-4 text-amber-600" />
                <span className="text-xl">⚡</span>
                <span className="font-semibold">Metal</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Metal ores are mined from earth</span>
              </div>
              <div className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-900/20 rounded-lg">
                <span className="text-xl">⚡</span>
                <span className="font-semibold">Metal</span>
                <ArrowRight className="h-4 w-4 text-gray-600" />
                <span className="text-xl">💧</span>
                <span className="font-semibold">Water</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Metal can be melted or condenses water</span>
              </div>
              <div className="flex items-center gap-3 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                <span className="text-xl">💧</span>
                <span className="font-semibold">Water</span>
                <ArrowRight className="h-4 w-4 text-blue-600" />
                <span className="text-xl">🌱</span>
                <span className="font-semibold">Wood</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Water nourishes trees and plants</span>
              </div>
            </div>
            <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
              <p className="text-sm text-blue-800 dark:text-blue-200">
                <strong>Cycle visualization:</strong> Wood → Fire → Earth → Metal → Water → Wood...
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Destruction Cycle */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <RefreshCw className="h-5 w-5 text-red-600" />
              2. The Destruction / Overcoming Cycle (相克 - xiāngkè)
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              This cycle describes how each element can overcome or control another, representing a relationship of balance and regulation. This cycle prevents any single element from becoming too powerful.
            </p>
            <div className="space-y-3">
              <div className="flex items-center gap-3 p-3 bg-green-50 dark:bg-green-900/20 rounded-lg">
                <span className="text-xl">🌱</span>
                <span className="font-semibold">Wood</span>
                <RefreshCw className="h-4 w-4 text-red-600" />
                <span className="text-xl">🌍</span>
                <span className="font-semibold">Earth</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Tree roots break through soil</span>
              </div>
              <div className="flex items-center gap-3 p-3 bg-amber-50 dark:bg-amber-900/20 rounded-lg">
                <span className="text-xl">🌍</span>
                <span className="font-semibold">Earth</span>
                <RefreshCw className="h-4 w-4 text-red-600" />
                <span className="text-xl">💧</span>
                <span className="font-semibold">Water</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Earth absorbs water or contains it</span>
              </div>
              <div className="flex items-center gap-3 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                <span className="text-xl">💧</span>
                <span className="font-semibold">Water</span>
                <RefreshCw className="h-4 w-4 text-red-600" />
                <span className="text-xl">🔥</span>
                <span className="font-semibold">Fire</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Water extinguishes fire</span>
              </div>
              <div className="flex items-center gap-3 p-3 bg-red-50 dark:bg-red-900/20 rounded-lg">
                <span className="text-xl">🔥</span>
                <span className="font-semibold">Fire</span>
                <RefreshCw className="h-4 w-4 text-red-600" />
                <span className="text-xl">⚡</span>
                <span className="font-semibold">Metal</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Intense heat melts metal</span>
              </div>
              <div className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-900/20 rounded-lg">
                <span className="text-xl">⚡</span>
                <span className="font-semibold">Metal</span>
                <RefreshCw className="h-4 w-4 text-red-600" />
                <span className="text-xl">🌱</span>
                <span className="font-semibold">Wood</span>
                <span className="text-sm text-gray-600 dark:text-gray-400">- Metal axe cuts down trees</span>
              </div>
            </div>
            <div className="mt-4 p-3 bg-red-50 dark:bg-red-900/20 rounded-lg">
              <p className="text-sm text-red-800 dark:text-red-200">
                <strong>Cycle visualization:</strong> Wood → Earth → Water → Fire → Metal → Wood...
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Summary Table */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Info className="h-5 w-5 text-blue-600" />
              Summary Table
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse border border-gray-300 dark:border-gray-600">
                <thead>
                  <tr className="bg-gray-50 dark:bg-gray-800">
                    <th className="border border-gray-300 dark:border-gray-600 p-3 text-left font-semibold">Element</th>
                    <th className="border border-gray-300 dark:border-gray-600 p-3 text-left font-semibold">Generates (生)</th>
                    <th className="border border-gray-300 dark:border-gray-600 p-3 text-left font-semibold">Is Generated By (被生)</th>
                    <th className="border border-gray-300 dark:border-gray-600 p-3 text-left font-semibold">Destroys (克)</th>
                    <th className="border border-gray-300 dark:border-gray-600 p-3 text-left font-semibold">Is Destroyed By (被克)</th>
                  </tr>
                </thead>
                <tbody>
                  {elements.map((element) => (
                    <tr key={element.name} className="hover:bg-gray-50 dark:hover:bg-gray-800/50">
                      <td className="border border-gray-300 dark:border-gray-600 p-3">
                        <div className="flex items-center gap-2">
                          <span className="text-lg">{element.emoji}</span>
                          <strong>{element.name.split(' ')[0]}</strong>
                        </div>
                      </td>
                      <td className="border border-gray-300 dark:border-gray-600 p-3">{element.generates}</td>
                      <td className="border border-gray-300 dark:border-gray-600 p-3">{element.generatedBy}</td>
                      <td className="border border-gray-300 dark:border-gray-600 p-3">{element.destroys}</td>
                      <td className="border border-gray-300 dark:border-gray-600 p-3">{element.destroyedBy}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>

        {/* Applications */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Star className="h-5 w-5 text-yellow-600" />
              Traditional Applications
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              These two cycles are fundamental to many traditional Chinese practices:
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {applications.map((app) => (
                <Card key={app.title} className={`${app.color} border`}>
                  <CardContent className="p-4">
                    <div className="flex items-start gap-3">
                      <span className="text-2xl">{app.icon}</span>
                      <div>
                        <h3 className="font-semibold text-lg mb-1">{app.title}</h3>
                        <p className="text-sm text-gray-600 dark:text-gray-400">{app.description}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Navigation */}
        <div className="flex justify-between items-center pt-6 border-t">
          <Button
            variant="outline"
            onClick={() => router.push('/en/wiki/wuxing')}
            className="flex items-center gap-2"
          >
            <ArrowLeft className="h-4 w-4" />
            Five Elements Wiki
          </Button>
          <Button
            variant="outline"
            onClick={() => router.push('/en/wiki/bazi')}
            className="flex items-center gap-2"
          >
            BaZi Wiki
            <ArrowRight className="h-4 w-4" />
          </Button>
        </div>
      </div>
    </EnglishLayout>
  )
} 